// Re-export all component prop types for external use

export type { QAlertProps } from './components/Alert/QAlert.component.vue'
export type { QAvatarProps } from './components/Avatar/QAvatar.component.vue'
export type { QBadgeProps } from './components/Badge/QBadge.component.vue'
export type { QButtonProps } from './components/Button/QButton.component.vue'
export type { QDetailsProps } from './components/Details/QDetails.component.vue'
export type { QDialogProps } from './components/Dialog/QDialog.component.vue'
export type { QDividerProps } from './components/Divider/QDivider.component.vue'
export type { QDrawerProps } from './components/Drawer/QDrawer.component.vue'
export type { QFlexProps } from './components/Flex/QFlex.component.vue'
export type { QFormFieldProps } from './components/Form/QFormField.component.vue'
export type { QGridProps } from './components/Grid/QGrid.component.vue'
export type { QGridItemProps } from './components/Grid/QGridItem.component.vue'
export type { QIconButtonProps } from './components/IconButton/QIconButton.component.vue'
export type { QInputProps } from './components/Input/QInput.component.vue'
export type { QMenuItemProps } from './components/Menu/QMenuItem.component.vue'
export type { QPopupProps } from './components/Popup/QPopup.component.vue'
export type { QSkeletonProps } from './components/Skeleton/QSkeleton.component.vue'
export type { QTabProps } from './components/Tabs/QTab.component.vue'
export type { QToastStackProps } from './components/Toast/QToastStack.component.vue'

// Export Placement type from QPopup
export type Placement =
  | 'top'
  | 'top-start'
  | 'top-end'
  | 'bottom'
  | 'bottom-start'
  | 'bottom-end'
  | 'right'
  | 'right-start'
  | 'right-end'
  | 'left'
  | 'left-start'
  | 'left-end'
